library/routes/web.php
<?php

use App\Http\Controllers\BooksController;
use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('books', BooksController::class);
Route::resource('categories', CategoryController::class);

library/app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    public $table = 'category';

    protected $fillable = ['name', 'description'];

    protected static function boot(){
        
        parent::boot();

        self::creating(function ($table){
            if( ! app()-> runningInConsole() ){

                $table -> user_id = auth() -> id();

            }
        });

    }

    public function user(){

        return $this -> belongsTo(User::class);

    }

}

library/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    public function __construct(){
        $this -> middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = Category::with('user')->paginate(10);
        return view('categories.index', compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = new Category;
        $title = __("Create a new category");
        $textButton = __("Create");
        $route = route("categories.store");
        return view( "categories.createCategory", compact("title", "textButton", "route", "category") );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this -> validate($request, [
            "name" => "required|unique:category",
            "description" => "nullable|string"

        ]);

        Category::create($request -> only("name", "description"));
        return redirect( route("categories.index") )
            ->with("success", __("Category has been created!"));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $update = true;
        $title = __("Update Category");
        $textButton = __("Update");
        $route = route("categories.update", ["category" => $category]);
        return view("categories.editCategory", compact("update", "title", "textButton", "route", "category"));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this -> validate($request, [

            "name" => "required|unique:category,name," . $category -> id,
            "description" => "nullable|string"

        ]);

        $category -> fill( $request -> only("name", "description")) -> save();
        return back() -> with("success", "Category has been updated!");

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category -> delete();

        return back() -> with("success", ("Category has been deleted!"));

    }
}

library/resources/views/categories/createCategory.blade.php
@extends("layouts.app")


@section("content")

    <div class="flex justify-center flex-wrap p-4 mt-5">
    
        @include("categories.formCategory")

    </div>

@endsection

library/resources/views/categories/editCategory.blade.php
@extends("layouts.app")


@section("content")

    <div class="flex justify-center flex-wrap p-4 mt-5">
    
        @include("categories.formCategory")

    </div>

@endsection

library/resources/views/categories/formCategory.blade.php
<div class="w-full max-w-lg">

    <div class="flex flex-wrap">
    
        <h1 class="mb-5"> {{ __("$title") }} </h1>

        <form class="w-full max-w-lg" method="POST" action="{{ $route }}">

        @csrf
        @isset($update)
            @method("PUT")
        @endisset

        <!-- Name of Category -->
        <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full px-3">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="name">
                    {{ __("Name") }}
                </label>
                <input name="name" value=" {{ old('name') ?? $category -> name }}" class="no-resize appareance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 resize-none" type="text">
                <!-- <p class="text-gray-600 text-xs italic mt-3"> {{ __("Name of the book") }} </p> -->
                @error("name")

                    <div class="border border-red-400 rounded-b bg-red-100 mt-1 px-4 py-3 text-red-700">
                        {{ $message }}
                    </div>

                @enderror
            </div>
        </div>


        <!-- Description of Category -->
        <div class="flex flex-wrap -mx-3 mb-6">

            <div class="w-full px-3">
            
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="description">
                    {{ __("Description") }}
                </label>

                <textarea name="description" id="description" class="no-resize appareance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 h-48 resize-none" cols="30" rows="10">{{ old("description") ?? $category -> description }}</textarea>

                @error("description")

                    <div class="border border-red-400 rounded-b bg-red-100 mt-1 px-4 py-3 text-red-700">
                        {{ $message }}
                    </div>

                @enderror
            
            </div>

        </div>

        <div class="md:flex md:items-center">

            <div class="md:2-1/3">
            
                <button class="shadow bg-teal-400 hover:bg-teal-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" type="submit">
                    {{ $textButton }}
                </button>

            </div>

        </div>

        </form>


    </div>

</div>

library/resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')


    <div class="flex justify-center flex-wrap bg-gray-200 p-4 mt-5">

        <div class="text-center">
        
            <h1 class="mb-5">
                {{ __("List of categories") }}
            </h1>

            <a href="{{ route('categories.create') }}" class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
            
                {{ __('Create a new category') }}

            </a>

        </div>

    </div>

    <table class="border-separate border-2 text-center border-gray-500 mt-3" style="width: 100%;">

        <thead>
            <tr>
            
                <th class="px-4 py2">{{ __('Name') }}</th>
                <th class="px-4 py2">{{ __('Description') }}</th>
            
            </tr>
        
        </thead>

        <tbody>
        
            @forelse( $category as $cat )

                <tr>
                    <td class="border px-4 py-2">{{ $cat -> name }}</td>
                    <td class="border px-4 py-2">{{ $cat -> description }}</td>
                    <td class="border px-4 py-2">
                        <a href="{{ route('categories.edit', ['category' => $cat]) }}" class="text-blue-400"> {{ __('Edit') }} </a>

                        <a 
                            href="#"
                            class="text-red-400"
                            onclick="event.preventDefault();
                                    document.getElementById('delete-category-{{ $cat -> id }}-form').submit();"
                        >{{ __('Delete') }}
                        </a>

                        <form id="delete-category-{{ $cat -> id }}-form" action="{{ route('categories.destroy', ['category' => $cat]) }}" method="POST" class="hidden">

                            @method("DELETE")
                            @csrf

                        </form>

                    </td>
                    
                </tr>

            @empty

                <tr>

                    <td colspan="5">
                        
                        <div class="bg-red-100 text-center border border-red-400 text-red-700 px-4 py-3">
                        
                            <p>
                                <strong class="font-bold">
                                    {{ __("There are no categories") }}
                                </strong>
                                <span class="block sm:inline">
                                    {{ __("registered yet") }}
                                </span>
                            </p>
                        
                        </div>

                    </td>
                
                </tr>

            @endforelse
        
        </tbody>
    
    </table>

    @if( $category -> count() )
        
        <div class="mt-3">
        
            {{ $category -> links() }}
        
        </div>

    @endif

@endsection