library/routes/web.php
<?php

use App\Http\Controllers\BooksController;
use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('books', BooksController::class);
Route::resource('categories', CategoryController::class);

library/app/Models/Books.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Books extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'author', 'user_borrowing', 'publication_date', 'category'];

    protected static function boot(){
        
        parent::boot();

        self::creating(function ($table){
            if( ! app()-> runningInConsole() ){

                $table -> user_id = auth() -> id();

            }
        });

    }

    public function user(){

        return $this -> belongsTo(User::class);

    }


}

library/app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use App\Models\Books;
use App\Models\Category;
use App\Models\User;
use Illuminate\Http\Request;

class BooksController extends Controller
{

    public function __construct(){
        $this -> middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Books::with('user')->paginate(10);
        return view('books.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $book = new Books;
        $category = Category::all();
        $users = User::all();
        $title = __("Create a new book");
        $textButton = __("Create");
        $route = route("books.store");
        return view( "books.createBook", compact("title", "textButton", "route", "book", "category", "users") );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this -> validate($request, [

            "name" => "required|unique:books",
            "author" => "nullable|string",
            "publication_date" => "nullable|string",
            "user_borrowing" => "nullable",
            "category" => "nullable|string"
        ]);
        
        //dd($request);

        Books::create($request -> only("name", "author", "publication_date", "category", "user_borrowing"));
        return redirect( route("books.index") )
            ->with("success", __("Book has been created!"));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Books  $books
     * @return \Illuminate\Http\Response
     */
    public function show(Books $books)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Books  $books
     * @return \Illuminate\Http\Response
     */
    public function edit(Books $book)
    {
        $update = true;
        $title = __("Update book");
        $category = Category::all();
        $users = User::all();
        $textButton = __("Update");
        $route = route("books.update", ['book' => $book]);
        return view("books.editBook", compact("update", "title", "textButton", "route", "book", "category", "users"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Books  $books
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Books $book)
    {
        $this -> validate($request, [

            "name" => "required|unique:books,name," . $book -> id,
            "author" => "nullable|string",
            "category" => "nullable|string",
            "publication_date" => "nullable|string",
            "user_borrowing" => "nullable|string"

        ]);

        $book -> fill( $request -> only("name", "author", "category", "publication_date", "user_borrowing")) -> save();
        return back() -> with("success", "¡Book has been updated!");

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Books  $books
     * @return \Illuminate\Http\Response
     */
    public function destroy(Books $book)
    {
        $book -> delete();

        return back() -> with("success", ("Book has been deleted!"));
    }
}

library/resources/views/books/createBook.blade.php
@extends("layouts.app")


@section("content")

    <div class="flex justify-center flex-wrap p-4 mt-5">
    
        @include("books.formBook")

    </div>

@endsection

library/resources/views/books/editBook.blade.php
@extends("layouts.app")


@section("content")

    <div class="flex justify-center flex-wrap p-4 mt-5">
    
        @include("books.formBook")

    </div>

@endsection

library/resources/views/books/formBook.blade.php
<div class="w-full max-w-lg">

    <div class="flex flex-wrap">
    
        <h1 class="mb-5"> {{ __("$title") }} </h1>

        <form class="w-full max-w-lg" method="POST" action="{{ $route }}">
        
        @csrf
        @isset($update)
            @method("PUT")
        @endisset

        <!-- Name of book -->
        <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full px-3">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="name">
                    {{ __("Name") }}
                </label>
                <input name="name" value="{{ old('name') ?? $book -> name }}" class="no-resize appareance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 resize-none" type="text">
                @error("name")

                    <div class="border border-red-400 rounded-b bg-red-100 mt-1 px-4 py-3 text-red-700">
                        {{ $message }}
                    </div>

                @enderror
            </div>
        </div>

        <!-- Author of book -->
        <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full px-3">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="author">
                    {{ __("Author") }}
                </label>
                <input name="author" value="{{ old('author') ?? $book -> author }}" class="no-resize appareance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 resize-none" type="text">
                @error("author")

                    <div class="border border-red-400 rounded-b bg-red-100 mt-1 px-4 py-3 text-red-700">
                        {{ $message }}
                    </div>

                @enderror
            </div>
        </div>


        <!-- Category of book -->
        <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full px-3">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="category">
                    {{ __("Category") }}
                </label>
            
                <select id="category" name="category" class="no-resize appareance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 resize-none">
                        <option value="">Ninguna</option>
                        @forelse( $category as $cat )
                            <option value="{{ $cat -> name }}" {{ $book -> category == $cat -> name ? 'selected' : ''  }} name="{{ $cat -> name }}" id="{{ $cat -> id }}" >{{ $cat -> name }}</option>
                        @empty
                        @endforelse
                </select>

            </div>
        </div>

        <!-- Borrow a book -->
        <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full px-3">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="user_borrowing">
                    {{ __("Borrow a book") }}
                </label>
            
                <select id="user_borrowing" name="user_borrowing" class="no-resize appareance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 resize-none">
                        <option value="">Available</option>
                        @forelse( $users as $user )
                            <option value="{{ $user -> name }}" {{ $book -> user_borrowing == $user -> name ? 'selected' : ''  }} name="{{ $user -> name }}" id="{{ $user -> id }}" >{{$user -> name }}</option>
                        @empty
                        @endforelse
                </select>

            </div>
        </div>

        <!-- Author of book -->
        <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full px-3">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="publication_date">
                    {{ __("Publication date") }}
                </label>
                <input name="publication_date" value=" {{ old('publication_date') ?? $book -> publication_date }}" class="no-resize appareance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 resize-none" type="text">
                @error("author")

                    <div class="border border-red-400 rounded-b bg-red-100 mt-1 px-4 py-3 text-red-700">
                        {{ $message }}
                    </div>

                @enderror
            </div>
        </div>

        <div class="md:flex md:items-center">

            <div class="md:2-1/3">
            
                <button class="shadow bg-teal-400 hover:bg-teal-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" type="submit">
                    {{ $textButton }}
                </button>

            </div>

        </div>

        </form>


    </div>

</div>

library/resources/views/books/index.blade.php
@extends('layouts.app')

@section('content')


    <div class="flex justify-center flex-wrap bg-gray-200 p-4 mt-5">

        <div class="text-center">
        
            <h1 class="mb-5">
                {{ __("List of books") }}
            </h1>

            <a href="{{ route('books.create') }}" class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
            
                {{ __('Create a new book') }}

            </a>

        </div>

    </div>

    <table class="border-separate border-2 text-center border-gray-500 mt-3" style="width: 100%;">

        <thead>
            <tr>
            
                <th class="px-4 py2">{{ __('Name') }}</th>
                <th class="px-4 py2">{{ __('Author') }}</th>
                <th class="px-4 py2">{{ __('Category') }}</th>
                <th class="px-4 py2">{{ __('Publication date') }}</th>
                <th class="px-4 py2">{{ __('Available') }}</th>
                <th class="px-4 py2">{{ __('Actions') }}</th>
            
            </tr>
        
        </thead>

        <tbody>
        
            @forelse( $books as $book )

                <tr>
                    <td class="border px-4 py-2">{{ $book -> name }}</td>
                    <td class="border px-4 py-2">{{ $book -> user -> name }}</td>
                    <td class="border px-4 py-2">{{ $book -> category }}</td>
                    <td class="border px-4 py-2">{{ $book -> publication_date }}</td>
                    <td class="border px-4 py-2">

                        @if ( isset($book -> user_borrowing) )
                            {{ __("Borrowed by" ) }} {{ $book -> user_borrowing }}
                        @else
                            {{ __("Available") }}
                        @endif 

                    </td>
                    <td class="border px-4 py-2">

                        <a href="{{ route('books.edit', ['book' => $book]) }}" class="text-blue-400"> {{ __('Edit') }} </a>

                        <a 
                            href="#"
                            class="text-red-400"
                            onclick="event.preventDefault();
                                    document.getElementById('delete-book-{{ $book -> id }}-form').submit();"
                        >{{ __('Delete') }}
                        </a>

                        <form id="delete-book-{{ $book -> id }}-form" action="{{ route('books.destroy', ['book' => $book]) }}" method="POST" class="hidden">

                            @method("DELETE")
                            @csrf

                        </form>

                    </td>
                    
                </tr>

            @empty

                <tr>

                    <td colspan="6">
                        
                        <div class="bg-red-100 text-center border border-red-400 text-red-700 px-4 py-3">
                        
                            <p>
                                <strong class="font-bold">
                                    {{ __("There are no books") }}
                                </strong>
                                <span class="block sm:inline">
                                    {{ __("registered yet") }}
                                </span>
                            </p>
                        
                        </div>

                    </td>
                
                </tr>

            @endforelse
        
        </tbody>
    
    </table>

    @if( $books -> count() )
        
        <div class="mt-3">
        
            {{ $books -> links() }}
        
        </div>

    @endif


@endsection